export enum PostoGraduacaoEnum {
  GEN_EX = 'gen ex',
  GEN_DIV = 'gen div',
  GEN_BDA = 'gen bda',
  CEL = 'cel',
  TEN_CEL = 'ten cel',
  MAJ = 'maj',
  CAP = 'cap',
  _1O_TEN = '1º ten',
  _2O_TEN = '2º ten',
  S_TEN = 's ten',
  _1O_SGT = '1º sgt',
  _2O_SGT = '2º sgt',
  _3O_SGT = '3º sgt',
  CIVIL = 'civil',
}
